source 'https://rubygems.org'

gem 'dashing'
gem 'hirb'
gem 'rspec'
gem 'pry'
gem 'pry-doc'
gem 'thor'
gem 'fog'
gem 'mysql2'


## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.0.0'